title: Colorado Springs Pro Public Education Group
logo: "/assets/logo.jpg"
subtitle: "Supporting public education in Colorado Springs"
baseurl: ""
url: "https://206.81.0.78"

markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap

sass:
  load_paths:
    - _sass

header_pages:
  - mission.md
  - contact.md
